# Generated by Django 3.2.5 on 2022-07-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('NAME', models.CharField(max_length=30)),
                ('SEM', models.CharField(max_length=20)),
                ('DEPT', models.CharField(max_length=100)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('TE', models.IntegerField(default=0, null=True)),
                ('photo', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_merchant', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_office', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
